FROM node

RUN mkdir -p /app/reports
RUN mkdir -p /app/frontend

WORKDIR /app/frontend

COPY package*.json /app/frontend/

RUN npm install

COPY . /app/frontend/

WORKDIR /app/frontend

RUN mkdir -p /app/frontend/public/reports
RUN ln -s /app/reports ./public/reports

CMD ["npm", "start"]